config/routes.rb
Rails.application.routes.draw do
  root to: "static#home"

  #users
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users do 
    resources :jots
  end
  
  resources :users do
    resources :jewels
  end

  resources :users do 
    member do get :followers, :following
    end
  end

  #relationships
  resources :relationships, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  #jots
  post '/users/:id/jots/new', to: 'jots#create' 
  post '/users/:id/jots/:id/edit', to: 'jots#update'
  get '/users/sign_out', to: 'jots#home'


  #jewels
  patch '/jewels', to: 'jewels#update'
  get 'jewels/all', to: 'jewels#index'
  get '/jot/:id/jewels/:id', to: 'jewels#show'
  post '/users/:id/jewels/:id', to: 'jewels#update'

end

app/models/jewel.rb
class Jewel < ApplicationRecord
    belongs_to :jot, optional: true
    has_one :user, through: :jot
 
end

app/controllers/jewels_controller.rb
class JewelsController < ApplicationController
    before_action :set_jewel, only: [:edit, :show]

	def home
		@jot = Jot.new
		@jewel = Jewel.new
	end

	def index
		@jewels = current_user.jewels
	end

  def new
    @user = User.find(params[:user_id])
    @jot = @user.jots.last
    @jewel = @user.jewels.build
	end

  def create
		@jewel = Jewel.new(jewel_params)
		@jot = Jot.find(params[:jewel][:jot_id])
		if @jewel.save
			redirect_to user_jewel_path(current_user, @jewel)
		else
			redirect_to new_jewel_path 
		end
	end
	
  def show
	end

  def edit
    @user = User.find(params[:user_id])
    @jot = @jewel.jot
	end

  def update
		@jewel = Jewel.find(params[:id])
		@jot = Jot.find(params[:jewel][:jot_id])
		redirect_to user_jewel_path([current_user, @jewel])
	end

	private 
	
	def jewel_params
		params.require(:jewel).permit(:id, :body, :jot_id)
	end

	def set_jewel
    @jewel = Jewel.find(params[:id])
  end
end

app/helpers/jewels_helper.rb
module JewelsHelper
end

app/views/jewels/_form.html.erb
<%= form_for [user, jewel] do |f| %>
  <%= f.hidden_field :jot_id, value: jot.id %>
	<%= f.text_field :body %>
	<br>
	<%= f.submit %>
<% end %>

app/views/jewels/edit.html.erb
<%= render partial: 'form', locals: {jewel: @jewel, jot: @jot, user: @user}  %>

<%= link_to 'See the Jot that Inspired It', user_jot_path(current_user, @jewel.jot) %>

app/views/jewels/index.html.erb
<% if @jewels.count > 0 %>
  <% @jewels.each do |jewel|%>
    <%= jewel.body %>
    <br>
    <%= link_to 'See Jewel', user_jewel_path(current_user, jewel) %>
  <% end %>

  <% else %>
    You have no jewels yet! Make a jot then make your jewel.

  <% end %>

app/views/jewels/new.html.erb
<%= render 'jewels/form', locals: {user: @user, jewel: @jewel, jot: @jot} %>

app/views/jewels/show.html.erb
<%= @jewel.body %>
<br>

<%= link_to "Edit Jewel", edit_user_jewel_path(current_user, @jewel) %>
<br>
<%= link_to "See the Jot that Inspired It", user_jot_path(current_user, @jewel.jot) %>