config/routes.rb
Rails.application.routes.draw do
  root to: "static#home"

  #users
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users do 
    resources :jots
  end
  
  resources :users do
    resources :jewels
  end

  resources :users do 
    member do get :followers, :following
    end
  end

  #relationships
  resources :relationships, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  #jots
  post '/users/:id/jots/new', to: 'jots#create' 
  post '/users/:id/jots/:id/edit', to: 'jots#update'
  get '/users/sign_out', to: 'jots#home'


  #jewels
  patch '/jewels', to: 'jewels#update'
  get 'jewels/all', to: 'jewels#index'
  get '/jot/:id/jewels/:id', to: 'jewels#show'
  post '/users/:id/jewels/:id', to: 'jewels#update'

end

app/models/jot.rb
class Jot < ApplicationRecord
  belongs_to :user, optional: true
	has_one :jewel
	
  validates :body, presence: true
  validates :title, presence: true


end

app/controllers/jots_controller.rb
class JotsController < ApplicationController
	before_action :set_jot, only: [:edit, :show]

	def home
		if current_user.member_signed_in?
			@jot = Jot.new
			@followers = current_user.following
			@user = current_user
		else 
			redirect_to not_signed_in_home_path
		end
	end

	def index
		@user = User.find(params[:user_id])
		@jots = @user.jots
	end

	def new
		@user = User.find(params[:user_id])
		@jot = @user.jots.build
	end

	def create
    @user = User.find(params[:user_id])
    @jot = Jot.new(jot_parameters(:title, :body, :user_id))
		if @jot.save
			redirect_to user_jot_path(current_user, @jot)
		else
			render 'jots/new'
		end
	end
	
	def show
		@user = User.find(params[:user_id])
    @jot = @user.jots.find(params[:id])
    @jewel = @user.jewels.build
	end

  def edit
		@user = current_user.id
	end

	def update
    @jot = Jot.update(title: params[:jot][:title], user_id: params[:jot][:user_id], body: params[:jot][:body])	
		redirect_to user_jot_path(current_user, @jot)
  end
  
  private 
  
  def jot_parameters(*args)
		params.require(:jot).permit(*args)
  end

  def set_jot
    @jot = Jot.find(params[:id])
  end

end

app/views/jots/_form.html.erb
<%= form_for [user, jot]  do |f| %>
<% if jot.errors.any? %>
    <% jot.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
  <br>
  <br>
  Start Jotting
  <br>
  <br>
  Title<%= f.text_field :title %>
  <br>
  <br>
  <%= hidden_field_tag '[jot][user_id]', current_user.id %>
  Jot
  <br>
  <%= f.text_area :body, size: "60x12" %>
    <%= f.submit %>
<% end %>

app/views/jots/edit.html.erb
<%= render partial: 'form', locals: {user: current_user, jot: @jot } %>

app/views/jots/index.html.erb
<% if @jots.count > 0 %>
		<% @jots.each do |jot|%>
		<br>
			<strong><%= link_to jot.title, user_jot_path(@user, jot) %></strong>
			<br>
			<br>
			<%= jot.body%>
			<br>
			<br>
			<%= jot.created_at.strftime(" %A, %B %d - %Y") %>
			<% end %>
	<% else %>
		<%= link_to 'You have no Jots Yet, Create a Jot Here', new_user_jot_path %>
	<% end %>

app/views/jots/new.html.erb
<%= render partial: 'form', locals: {user: current_user, jot: @jot } %>

app/views/jots/show.html.erb
<% if !current_user.jots.empty? %>
	<strong>Title: </strong>
	<br>
	<%= @jot.title %>
	<br>

	<strong>Body:</strong> <br>

	<%= @jot.body %>
	<br>
	<%= link_to 'Edit Jot', edit_user_jot_path(@jot) %>
	<br>
	<br>

		<% if @jewel.body %>
      <%= @jewel.body %>
			<% else %>
			<%= link_to 'Create Jewel', new_user_jewel_path(@user, @jewel) %>
		<% end %>
		<% else %>
			<%= There are no jots %>
		<% end %>

app/views/jots/signed_in_home.html.erb
 <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

<% if current_user %>
    <% if current_user.low_following_count? %>
    <%= User.most_popular.each do |user|%>
          <br>
          <%= user.first_name %>
          <br>
          <%= user.last_name%>
          <br>
          <%= button_to("Follow", (current_user.follow(user))) %>

          <% end %>
      <% else %>
        <%= User.most_popular.each do |user|%>
          <%= @jots.each do |jot|%>
          <%= jot.title %>
          <%= jot.body %>
          <% end %>
    <% end %>
    <% end %>
  <% end %>


<%= link_to 'Create Jot', new_jot_path(@jot) %>

<%= link_to 'My Jots', jots_path %>

<%= link_to 'My Jewels', jewels_path %>

<br>

<%= render 'shared/stats' %>